config/routes.rb
Rails.application.routes.draw do
  resources :websites
  root to: 'websites#index'


  match 'websites/:id/check_now' => 'websites#check_now', as: :check_now, via: :get


end

app/models/Ping.rb
require 'net/http'
require 'rufus-scheduler'

class Ping


	module Status
		OK        = "OK"
		NOT_OK    = "NOT_OK"
		UNCHECKED = "UNCHECKED"
	end

	attr_reader :url
	attr_reader :timestamp
	attr_reader :status

	@timeout
	@scheduler

	def initialize(url)
		@url = url
		@timeout = 10
		@status  = Status::UNCHECKED
	end

	def check
		@timestamp = Time.now
		@status = Ping.check(@url)
		return @status
	end

	private
	def self.check(url)
		url = URI.parse(url)
		req = Net::HTTP::Get.new(url.to_s)

		begin
			res = Net::HTTP.start(url.host, url.port) do |http|
				http.request(req)
			end

			case res.code
			when "200"
				status = Ping::Status::OK
			when "301"
				status = self.check(res.header['location'])
			else
				status = Ping::Status::NOT_OK
			end
		rescue Errno::ECONNREFUSED
			status = Ping::Status::NOT_OK
		end

		return status
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/website.rb
class Website < ApplicationRecord
	validates :url, presence: true
	enum status: [:ok, :not_ok, :unchecked]

	def check_now
		ping = Ping.new(self.url)
		self.status = ping.check.downcase
		self.lastchecked = ping.timestamp
		self.save
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :show_flash

  private

  def show_flash
    flash.now[:notice] = "Found the about page!" if request.path == '/pages/about'
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1
  # GET /websites/1.json
  def check_now
    @website = Website.find params[:id]
    @website.check_now
    render json: @website.to_json
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:url, :status, :lastchecked)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Uptime Monitor", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Uptime Monitor" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Uptime Monitor" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main class="container" role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>

<div class="jumbotron">
  <h1 class="display-4">About the Website</h1>
  <p class="lead">
    This web application was created with
    <%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
    from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
  </p>
</div>

app/views/visitors/index.html.erb
<div class="jumbotron">
  <h1 class="display-2">Welcome</h1>
  <p class="lead">
    This web application was created with
    <%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
    from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
  </p>
</div>

app/views/websites/_form.html.erb
<%= bootstrap_form_for(website) do |f| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/websites/edit.html.erb
<h1>Editing Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

app/views/websites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Websites</h1>

<table class="table">
  <thead>
    <tr>
      <th>Url</th>
      <th>Status</th>
      <th>Lastchecked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
    
    <% website.check_now %>

      <tr>
        <td><%= website.url %></td>
        <td><%= website.status %></td>
        <td><%= website.lastchecked %></td>
        <td><%= link_to 'Check Now', website, remote: true, class: 'link-check-now' %></td>
        <td><%= link_to 'Edit', edit_website_path(website) %></td>
        <td><%= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website', new_website_path, class: 'btn btn-primary' %>

app/views/websites/new.html.erb
<h1>New Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @website.url %>
</p>

<p>
  <strong>Status:</strong>
  <%= @website.status %>
</p>

<p>
  <strong>Lastchecked:</strong>
  <%= @website.lastchecked %>
</p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>